# Generated by Django 4.2.27 on 2026-01-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_latitude_equipment_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
